// Package bundler copies the sliced files into an output directory preserving
// the package layout the imports require, writes repro.sh, and emits a
// MANIFEST.md mapping each included file to the reason it was kept.
package bundler

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/kaeawc/reprobundle/internal/intake"
	"github.com/kaeawc/reprobundle/internal/slicer"
)

// Bundle is the input to Write. SrcFS is the repository filesystem the
// slicer worked from (so the bundler can read the same files), Files and
// External come straight from slicer.WalkFiles, and Seed is the original
// entry point so repro.sh and the manifest can describe the failure.
type Bundle struct {
	SrcFS    fs.FS
	Files    []string
	External []string
	Seed     intake.Seed
	// SrcRoot is the absolute on-disk path of the repository root. Only
	// used in the manifest header for human reference.
	SrcRoot string
}

// FromWalk is a convenience that fills the Files/External fields from a
// slicer.FileSet.
func FromWalk(srcFS fs.FS, srcRoot string, seed intake.Seed, set slicer.FileSet) Bundle {
	return Bundle{
		SrcFS:    srcFS,
		SrcRoot:  srcRoot,
		Seed:     seed,
		Files:    set.Files,
		External: set.External,
	}
}

// Write materialises the bundle under outDir. The directory is created if
// it does not already exist; existing files inside it are overwritten.
// Write does not delete files outDir already contains — callers that want
// a clean slate should remove and recreate it themselves.
func Write(outDir string, b Bundle) error {
	if outDir == "" {
		return fmt.Errorf("bundler: empty output directory")
	}
	if b.SrcFS == nil {
		return fmt.Errorf("bundler: nil source FS")
	}
	if len(b.Files) == 0 {
		return fmt.Errorf("bundler: bundle contains no files")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("bundler: mkdir %s: %w", outDir, err)
	}

	for _, rel := range b.Files {
		if err := copyOne(b.SrcFS, rel, outDir); err != nil {
			return err
		}
	}
	if err := writeManifest(outDir, b); err != nil {
		return err
	}
	return writeReproScript(outDir, b)
}

func copyOne(src fs.FS, rel, outDir string) error {
	cleaned := filepath.ToSlash(filepath.Clean(rel))
	if strings.HasPrefix(cleaned, "../") || filepath.IsAbs(cleaned) {
		return fmt.Errorf("bundler: refuse to copy %q (escapes repo root)", rel)
	}
	in, err := src.Open(cleaned)
	if err != nil {
		return fmt.Errorf("bundler: open %s: %w", rel, err)
	}
	defer in.Close()

	dst := filepath.Join(outDir, filepath.FromSlash(cleaned))
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("bundler: mkdir %s: %w", filepath.Dir(dst), err)
	}
	out, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("bundler: create %s: %w", dst, err)
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("bundler: copy %s: %w", rel, err)
	}
	return nil
}

func writeManifest(outDir string, b Bundle) error {
	var sb strings.Builder
	fmt.Fprintln(&sb, "# Reprobundle manifest")
	fmt.Fprintln(&sb)
	fmt.Fprintf(&sb, "Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	if b.SrcRoot != "" {
		fmt.Fprintf(&sb, "Source repo: %s\n", b.SrcRoot)
	}
	fmt.Fprintf(&sb, "Entry: %s\n", formatSeed(b.Seed))
	fmt.Fprintln(&sb)

	fmt.Fprintf(&sb, "## Files (%d)\n\n", len(b.Files))
	files := append([]string(nil), b.Files...)
	sort.Strings(files)
	for _, f := range files {
		reason := "reachable from entry"
		if isPackageInit(f) {
			reason = "parent package __init__"
		}
		if f == b.Seed.File {
			reason = "entry point"
		}
		fmt.Fprintf(&sb, "- `%s` — %s\n", f, reason)
	}

	if len(b.External) > 0 {
		fmt.Fprintf(&sb, "\n## External (%d)\n\n", len(b.External))
		fmt.Fprintln(&sb, "These imports were referenced but resolved outside the repo. The bundle does not include them; install them in the repro environment.")
		fmt.Fprintln(&sb)
		ext := append([]string(nil), b.External...)
		sort.Strings(ext)
		for _, e := range ext {
			fmt.Fprintf(&sb, "- `%s`\n", e)
		}
	}

	return os.WriteFile(filepath.Join(outDir, "MANIFEST.md"), []byte(sb.String()), 0o644)
}

func writeReproScript(outDir string, b Bundle) error {
	target := pytestTarget(b.Seed)
	body := fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by reprobundle. Run from this directory to reproduce the
# failure that produced this bundle.
set -euo pipefail
cd "$(dirname "$0")"
exec python -m pytest -x %q
`, target)
	path := filepath.Join(outDir, "repro.sh")
	return os.WriteFile(path, []byte(body), 0o755)
}

func pytestTarget(s intake.Seed) string {
	if s.Class != "" {
		base := s.File + "::" + s.Class + "::" + s.Symbol
		if s.Param != "" {
			base += "[" + s.Param + "]"
		}
		return base
	}
	base := s.File + "::" + s.Symbol
	if s.Param != "" {
		base += "[" + s.Param + "]"
	}
	return base
}

func formatSeed(s intake.Seed) string {
	out := s.File
	if s.Class != "" {
		out += "::" + s.Class
	}
	if s.Symbol != "" {
		out += "::" + s.Symbol
	}
	if s.Param != "" {
		out += "[" + s.Param + "]"
	}
	return out
}

func isPackageInit(p string) bool {
	return strings.HasSuffix(filepath.ToSlash(p), "/__init__.py") || filepath.ToSlash(p) == "__init__.py"
}
